// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvjnuObDGJ8Zs2Pac99JLFqDlxtIgeuCs',
    appId: '1:167938253702:android:d2a8c4924a074297844207',
    messagingSenderId: '167938253702',
    projectId: 'travella-firebase-5f0cb',
    databaseURL: 'https://travella-firebase-5f0cb-default-rtdb.firebaseio.com',
    storageBucket: 'travella-firebase-5f0cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALm6xcgQ2zhraRja26ucv69EolQP-VKos',
    appId: '1:167938253702:ios:7137029552f7894d844207',
    messagingSenderId: '167938253702',
    projectId: 'travella-firebase-5f0cb',
    databaseURL: 'https://travella-firebase-5f0cb-default-rtdb.firebaseio.com',
    storageBucket: 'travella-firebase-5f0cb.appspot.com',
    androidClientId: '167938253702-2ju15a5sifvk4q2jr60gnc6n58dv7tda.apps.googleusercontent.com',
    iosClientId: '167938253702-nnlv48uhk8dqg1d31rntfakndkamu6lk.apps.googleusercontent.com',
    iosBundleId: 'com.example.travella01',
  );
}
